'''
This is a setup.py script generated by py2applet
Usage: python setup.py py2app
repository: https://github.com/DanielSchuette/CalciumImagingAnalyzer.git
'''
import ez_setup
ez_setup.use_setuptools()
from setuptools import setup
# from distutils.core import setup
import py2app
from plistlib import Plist
import os
import sys

APP = ["sample.py"]
DATA_FILES = ["helpers.py"] 
ICON = "../data/if_application-x-python_8974.icns"
name = "CalciumImagingAnalyzer v0.02"
version = "0.0.2"

if sys.platform == "darwin":
    extra_options = dict(
        setup_requires=["py2app"],
        app=[APP],
        # Cross-platform applications generally expect sys.argv to
        # be used for opening files.
        options=dict(py2app=dict(argv_emulation=True)),
    )
elif sys.platform == "win32":
    extra_options = dict(
        setup_requires=["py2exe"],
        app=[APP],
    )
else:
     extra_options = dict(
         # Normally unix-like platforms will use "setup.py install"
         # and install the main script as such
         scripts=[APP],
)

setup(
    app=APP,
    data_files=DATA_FILES,
    options=dict(
    	py2app=dict(
    		iconfile=ICON,
    		packages=["matplotlib", "numpy", "keras", "tifffile", "pandas", "errno"], 
            # to try: "os", "Tkinter", "ttk", "tkMessageBox", "tkFileDialog",
            # does not want to import "time", "sys", "pylab"
    		site_packages=True,
    		resources=[ICON],
    		plist=dict(
    			CFBundleName = name,
                CFBundleDisplayName = name,
                CFBundleIdentifier = "Daniel Schuette",
                CFBundleVersion = 0.02,
    			CFBundleShortVersionString = version,
    			CFBundleGetInfoString = name+" "+ version,
    			CFBundleExecutable = name,
                NSHumanReadableCopyright = "Copyright (c)2018, Daniel Schuette, All Rights Reserved"
    		),
    	),
    ),
)